aherd2985/UtilityBelt

Program.cs
SecretsModel.cs
ServiceProviderBuilder.cs
UtilityBelt.csproj

Implemented .net core User Secrets, created method for sending text message to at&t cell phone

New functionality

---

Models/ChuckJokeModel.cs
Models/SecretsModel.cs
Program.cs
ServiceProviderBuilder.cs

Created new method for hitting the Chuck Norris API to display a random joke!!!

Hit API display Chuck Norris joke

---

Models/CatFactModel.cs
Program.cs

Created new method to hit api and display a cat fact

Created new method to hit api and display a cat fact

---

Models/BitcoinPrice.cs
Program.cs

Add hitting api to grab latest value for Bitcoin

Add hitting api to grab latest value for Bitcoin

---

Models/BitcoinPrice.cs
Models/CatFactModel.cs
Models/SpacePersonModel.cs
Program.cs

Created SpacePersonModel and better defined Model names

Created SpacePersonModel and better defined Model names

---

Program.cs

Created print out of people in space and aboard which aircraft from api

Created print out of people in space and aboard which aircraft from api

---

.vscode/launch.json
.vscode/tasks.json
Program.cs

A do while was added to show the menu to users

adding a way for the user to loop back to the Menu Options to try something else 

---

Models/SecretsModel.cs
Program.cs
ServiceProviderBuilder.cs

Hi!
In this PR I moved OpenWeatherMapApiKey to secrets.json file for prevent leaking of sensitive information.
I stick to already design architecture approach how to read secrets.
Thank you!
Have a nice day! 😄

Read OpenWeatherMapApiKey from secrets json.

---

Models/SecretsModel.cs
Program.cs
README.md
ServiceProviderBuilder.cs

Added an ability to send messages using Discord Webhooks.
Also edited README.md to look more pleasant, and added a new entry to secrets.json file

Discord Webhook Sender

---

Models/QuoteModel.cs
Program.cs

New option to display a random quote into the console window.
The quote is fetched from [api.forismatic.com](https://api.forismatic.com/api/1.0/?method=getQuote&lang=en&format=json)

New option to display a random quote into console

---

Models/EvilInsultModel.cs
Program.cs

#30 
added evil api as 11th command

added evil api

---

Models/TacoRecipeModel.cs
Program.cs

Uses http://taco-randomizer.herokuapp.com/ to generate a base, mixin, seasoning, condiment, and shell combination.

Added menu option 'Random Taco Recipe'

---

Models/Covid19.cs
Program.cs

Added 14th option that gives you covid-19 statistics in a chosen country. Uses api.covid19api.com.

Added menu option 'Covid-19 Statistics'

---

Models/AdviceModel
Models/AdviceModel.cs
Models/SpaceStationLocation.cs
Program.cs

Added in two new options for random advice and the international space station location. I also formatted the main program file for consistency.

Adding in Random Advice and International Space Station Location

---

Models/BreakingBadQuoteModel.cs
Program.cs

Case 23 - Breaking Bad quotes

---

Program.cs

Making the console application more fun!
For #42

Case 24 - Implemented Ghost Game

---

Program.cs
UtilityBelt.csproj

Allows you to type a DNS hostname and convert it to an IP Address.

Case 25 - DNS Hostname to IP Addresses

---

Models/PandaFactModel.cs
Program.cs

Returns a random panda fact. (Pandas are cute.)

Added panda fact module.

---

Models/AdviceModel.cs

made that change boss

---

Program.cs

- Added input validation to make sure it is the number 1,2, or 3.
- Excluded 0 from random number generation.
- Gets a new random number, if a ghost was not found.

Ghost game input check

---

Models/DigitalOceanStatusModel.cs
Program.cs
ServiceProviderBuilder.cs

Fixed indentation and case 28 - DigitalOcean status

---

Models/CookieSuspectModel.cs
Models/DadJokeModel.cs
Models/RandomUser.cs
Models/Weather.cs
Program.cs

Hello All,
This is my first commit to #hacktoberfest. I will be more active contributor to this project. Let us take small steps. 
In this commit, I have tried to fix following issues
1. Naming violation
2. Object initialization simplified
3. Remove unnecessary assignments
4. Use discard variable 
5. Part reformatting.

Fix naming rule violation warnings and messages

---

.gitignore
Logging/Logger.cs
Program.cs
UtilityBelt.csproj

Issue : 
https://github.com/aherd2985/UtilityBelt/issues/13
```hacktoberfest-2020```

Issue #13 - Implement Logging for Console Application

---

Program.cs

Added random fox fact module.

---

Models/ProgrammingQuoteModel.cs
Program.cs

Added the functionality to get a random programmer quote, which displays the quote as well as the author of the quote.

Add random programmer quote

---

Program.cs
Utilities/WeatherForecast.cs

According to new architecture style (MEF) I moved weather forecast to separate class.

Move weather forecast to utility class

---

Program.cs
Utilities/Calculator.cs

Also fixed divide by zero issue

Move and refactor calculator

---

Utilities/PortScanner.cs

Use `Parallel.ForEach` to speed up port scanning process. Currently `MaxDegreeOfParallelism` is set as 10 because when test scanning with Google, if `MaxDegreeOfParallelism` is too large, all sockets will receive response as the port is not open.

Parallel to do port scan

---

Tests/UtilityBeltxUnitTests/KanyeQuoteTests.cs
Utilities/BitcoinPrices.cs
Utilities/KanyeQuote.cs

[I ain't saying this was broke, broke](https://www.youtube.com/watch?v=6vwNcNOTVzY&feature=emb_logo)
Go head girl, go head get down 
smash this pr button down
check those unit tests logic now
this how we merge it now we say how
👾 - Adds unit tests for yeezus
😎 - Because I believe in my flyness... this conquers errors in my webClient.

adds tests to Kanye model, fixes uncaught error in Kanye and BitCoin

---

Models/BreakingBadQuoteModel.cs
Models/CatFactModel.cs
Tests/UtilityBeltxUnitTests/BreakingBadQuotesTests.cs
Tests/UtilityBeltxUnitTests/CatFactsTests.cs
Tests/UtilityBeltxUnitTests/UtilityBeltxUnitTests.csproj
Tests/UtilityBeltxUnitTests/WeatherForecastTests.cs
Tests/UtilityBeltxUnitTests/responseSamples/catFactResponse.json
Utilities/BreakingBadQuotes.cs
Utilities/CatFact.cs

Adds tests for BreakingBadQuotes and Catfacts.  The Catfacts tests include an example of how I like to handle items which give rich json results back, hopefully someone likes it!
Resolves #87

Completed tests for BreakingBadQuotes and Catfacts

---

Models/BirdFactModel.cs
Tests/UtilityBeltxUnitTests/BirdFactsTests.cs
Tests/UtilityBeltxUnitTests/UtilityBeltxUnitTests.csproj
Tests/UtilityBeltxUnitTests/responseSamples/birdFactResponse.json
Utilities/BirdFact.cs

🐦Adds new BirdFact utility and tests🦉

---

Models/YodaTranslationModel.cs
Utilities/YodaTranslation.cs

I've included a new module for Yoda translations
This is based on the api https://api.funtranslations.com/translate/yoda.json?text=
Let me know if you have any question or want me to make any change
Thank you!

Included Yoda translation module

---

Models/CookieSuspectModel.cs

Resolved the issue #93 in "WhoStoleTheCookie" utility issue by correcting previously incorrect CookieSuspect Model to consume input JSON data from API.

Resolved the issue in "WhoStoleTheCookie" utility/command. Closes #93

---

Utilities/DateDiffCalculator.cs

Examples of easy functionality commonly used in work situations

Created new utility for a simple Date Difference Calulculator

---

Models/CocktailDrinkModel.cs
Utilities/BirdFact.cs
Utilities/Cocktails.cs
Utilities/DateDiffCalculator.cs

Built out a Cocktail utility that will search by drink name and print out the ingredients and instructions for each match

Cocktail utility

---

Utilities/Cocktails.cs

Ask for a random Cocktail and it will print out a recipe with ingredients and instructions

Created a random Cocktail generator

---

Models/CocktailIngredientModel.cs
Utilities/Cocktails.cs

Created methods to search cocktail recipes by ingredients or get details on ingredients

Cocktail Ingredients

---

Models/SpaceXModel.cs
Utilities/SpaceX.cs

SpaceX offers some data about launch and so on, this is the first, but they are really interesting

SpaceX Data

---

Models/MagicCardModel.cs
Utilities/MagicTheGathering.cs

Added MagicTheGathering

---

Models/JokeModel.cs
Utilities/Joke.cs

Added Jokes!

---

Models/NextMarvelMovieModel.cs
Utilities/NextMarvelMovie.cs

When will be the next Marvel movie?
